name: Audit Infra Verification

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Verify Supabase connectivity
        env:
          PGURL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          set -euo pipefail
          echo "Checking connectivity to Supabase..."
          if ! psql "$PGURL" -c '\q'; then
            echo "❌ Failed to connect to Supabase database. Check network or credentials."
            exit 1
          fi
          echo "✅ Connectivity check passed."

      - name: Run audit verification
        env:
          PGURL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          set -euo pipefail
          echo "Running audit verification checks..."
          psql "$PGURL" -v ON_ERROR_STOP=1 -q -f db/audit_infra/09_continuous_verification.sql | tee verification.out

          if grep -qE '\bf\b' verification.out; then
            echo "❌ Audit verification failed"
            exit 1
          else
            echo "✅ Audit verification passed"
          fi
